{% set name = "easyquery" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/easyquery-{{ version }}.tar.gz
  sha256: fc4a0e8cb75a3213a366e1e67ef37d3d3d049cf4c3419882acb89281777f344e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numexpr >=2.0
    - numpy >=1.7
    - python >=3.6

test:
  imports:
    - easyquery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yymao/easyquery
  summary: Create easy-to-use Query objects that can apply on NumPy structured arrays, astropy Table, and Pandas DataFrame.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/yymao/easyquery/blob/master/README.md
  dev_url: https://github.com/yymao/easyquery

extra:
  recipe-maintainers:
    - yymao
